"""One generated stylesheet per page shell (each Observability view is a page).

tools/build_page_css.py writes them from the layered sources (src/static/css/,
see test_css_layers_contract.py) at build time (CMake, the Docker images): they
are not committed. Each keeps the rules that can match on its page, in the
cascade order of the sources.
"""
import re

import css_sources

PAGES = ["query", "explorer", "functions", "traces", "logs", "metrics", "trace", "system", "queries", "disks", "shape", "mcp"]
VIEWS = ["traces", "logs", "metrics"]
# Generated sheets: one per page shell.
SHEETS = [f"style.{page}.css" for page in PAGES]


def read(rel: str) -> str:
    return (css_sources.ROOT / rel).read_text(encoding="utf-8")


def test_each_page_shell_loads_its_own_generated_stylesheet():
    for page in PAGES:
        html = read(f"src/static/{page}.html")
        assert f'var cssHref = window.__chdashUrl("static/style.{page}.css")' in html, page
        assert 'window.__chdashUrl("static/style.css")' not in html, page
        assert "document.write('<link rel=\"stylesheet\" href=\"' + cssHref + '\">');" in html, page


def test_the_sheets_are_build_outputs_not_sources():
    assert sorted(css_sources.sheets()) == sorted(SHEETS)
    # Never committed: git ignores them, and the builds generate them.
    assert "/src/static/style.*.css" in read(".gitignore")
    cmake = read("src/CMakeLists.txt")
    assert '"${Python3_EXECUTABLE}" "${_CSS_TOOL}" --out "${_STATIC_STAGE}"' in cmake
    assert 'chdash_embed_directory("${_STATIC_STAGE}"' in cmake
    docker = read("tests/Dockerfile.source")
    assert "python3 /work/tools/build_page_css.py --out /work/src/static" in docker
    assert "COPY --from=static /work/src/static /app/static" in docker
    # The sources are not shipped: the stage drops them.
    assert 'PATTERN "css" EXCLUDE' in cmake and "rm -rf /work/src/static/css" in docker


def rule_lines(sheet: str) -> list[str]:
    """The rule lines of a generated sheet, in order (one rule per line)."""
    return [line.strip() for line in sheet.splitlines() if line.rstrip().endswith("}") and "{" in line]


def test_page_sheets_keep_the_cascade_order_and_drop_only_unmatchable_rules():
    builder = css_sources.builder()
    sheets = css_sources.sheets()
    full = rule_lines(builder.HEADER.format(page="all") + builder.sheet(None))
    for name in SHEETS:
        header, css = sheets[name].split("\n", 1)
        assert header.startswith("/* Generated by tools/build_page_css.py"), name
        assert css.startswith("@layer tokens, base, components, features, overrides;\n"), name
        # Every kept rule keeps its place: a subsequence of the full sheet, selectors
        # filtered, declarations verbatim.
        position = 0
        bodies = [line[line.index("{"):] for line in full]
        for line in rule_lines(css):
            body = line[line.index("{"):]
            position = bodies.index(body, position) + 1
        assert len(css) < len(builder.sheet(None)), name
    corpus = builder.page_corpus("traces")
    # Names assembled at run time count as present ("chdash-trace-tab-" + tab).
    assert corpus.has("chdash-trace-tab-services")
    # Lookups of an id another page owns do not keep that page's rules.
    assert not builder.page_corpus("logs").has("explorerDetailTabs")
    assert builder.selector_can_match(".traceX:not(.queryOnlyName)", corpus) == corpus.has("traceX")


def test_names_are_read_from_literals_not_from_comments_or_identifiers():
    builder = css_sources.builder()
    corpus = builder.Corpus(
        ['<div class="htmlName" data-x="dataWord"><script>const a = "inlineName";</script></div>'],
        [
            '// "commentName" in a comment\n'
            "/* 'blockComment' */\n"
            "const ns = { identifierName: 1 };\n"
            'el.className = "literalName " + kind;\n'
            'const re = /"regexName"/g;\n'
            "const tpl = `tplName ${cond ? \"nested\" : \"\"} chdash-tab-${tab}`;\n"
            'const node = byId("lookupName");\n',
        ],
    )
    for present in ("htmlName", "dataWord", "inlineName", "literalName", "tplName", "nested", "chdash-tab-x"):
        assert corpus.has(present), present
    for absent in ("commentName", "blockComment", "identifierName", "regexName", "lookupName", "literal"):
        assert not corpus.has(absent), absent


def test_observability_page_sheets_hold_their_view_and_the_shell():
    builder = css_sources.builder()
    # A view's page lists its own modules and its own markup, none of the other views'.
    logs = builder.page_modules("logs")
    assert "app_logs.js" in logs and "app_traces.js" not in logs and "app_metrics.js" not in logs
    assert "app_obs_page.js" in logs and "app_timerange.js" in logs
    assert 'id="tracesForm"' not in builder.shell_html("logs")
    assert 'id="logsForm"' in builder.shell_html("logs")
    sheets = css_sources.sheets()
    rules = {view: sheets[f"style.{view}.css"] for view in VIEWS}
    # Each sheet styles the shell (the view link row) and its own view only.
    for view, css in rules.items():
        assert re.search(r"^\s*\.obsNav \{", css, flags=re.M) and re.search(r"^\s*\.contentTabs__tab \{", css, flags=re.M), view
        assert "a.contentTabs__tab" in css, view
    assert ".logsTable__viewport" in rules["logs"] and ".logsTable__viewport" not in rules["traces"]
    assert ".metricsPanels" in rules["metrics"] and ".metricsPanels" not in rules["logs"]
    assert ".traceWaterfall" in rules["traces"] and ".traceWaterfall" not in rules["metrics"]


def test_query_and_explorer_skip_the_modules_they_never_run():
    builder = css_sources.builder()
    # One manifest (modules.json) lists each page's modules; app.js loads that list.
    assert "return loader.startModules();" in read("src/static/app.js")
    query = builder.page_modules("query")
    explorer = builder.page_modules("explorer")
    assert {"app_explorer.js", "app_run.js", "app_autocomplete.js", "app_analysis.js"} <= set(query)
    assert "app_explorer_graph.js" not in query and "app_explorer_treemap.js" not in query
    assert {"app_explorer.js", "app_explorer_graph.js", "app_explorer_treemap.js", "app_results.js", "app_highlight.js"} <= set(explorer)
    for name in ["app_autocomplete.js", "app_run.js", "app_analysis.js", "app_pipeline_viewer.js", "app_trace_viewer.js", "app_download.js", "app_export.js"]:
        assert name not in explorer, name
