import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PAGES = ["query", "explorer"]
VIEWS = ["traces", "logs", "metrics"]
# Generated sheets: one per page shell, one per Observability view, one for every view.
SHEETS = [f"style.{page}.css" for page in PAGES] + [f"style.observability.{view}.css" for view in VIEWS] + ["style.observability.css"]


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def load_builder():
    spec = importlib.util.spec_from_file_location("build_page_css", ROOT / "tools" / "build_page_css.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_each_page_shell_loads_its_own_generated_stylesheet():
    for page in PAGES:
        html = read(f"src/static/{page}.html")
        assert f'var cssHref = window.__chdashUrl("static/style.{page}.css")' in html, page
        assert 'window.__chdashUrl("static/style.css")' not in html, page
        assert "document.write('<link rel=\"stylesheet\" href=\"' + cssHref + '\">');" in html, page
    # Observability: the sheet of the view the URL (or the first enabled view) names.
    html = read("src/static/observability.html")
    assert 'var cssHref = window.__chdashUrl("static/style.observability." + view + ".css")' in html
    assert "document.write('<link rel=\"stylesheet\" href=\"' + cssHref + '\">');" in html
    assert 'window.__chdashUrl("static/style.css")' not in html


def test_generated_page_stylesheets_are_current():
    builder = load_builder()
    outputs = builder.build()
    assert sorted(path.name for path in outputs) == sorted(SHEETS)
    for path, text in outputs.items():
        assert path.is_file(), f"{path.name} missing: run python3 tools/build_page_css.py"
        assert path.read_text(encoding="utf-8") == text, f"{path.name} is stale: run python3 tools/build_page_css.py"


def test_page_stylesheets_keep_style_css_order_and_drop_only_unmatchable_rules():
    builder = load_builder()
    source = read("src/static/style.css")
    for page in SHEETS:
        header, css = read(f"src/static/{page}").split("\n", 1)
        assert header.startswith("/* Generated by tools/build_page_css.py"), page
        # Every kept rule is copied verbatim and in the original order.
        position = 0
        for prelude in re.findall(r"^([^{}@\s][^{}]*?) \{", css, flags=re.M)[:400]:
            found = re.compile(re.escape(prelude) + r"\s*\{").search(source, position)
            assert found, (page, prelude)
            position = found.start()
        assert len(css) < len(source), page
    corpus = builder.Corpus(builder.observability_corpus("traces"))
    # Names assembled at run time count as present ("chdash-trace-tab-" + tab).
    assert corpus.has("chdash-trace-tab-services")
    # Lookups of an id another page owns do not keep that page's rules.
    assert not builder.Corpus(builder.observability_corpus("logs")).has("explorerDetailTabs")
    assert builder.selector_can_match(".traceX:not(.queryOnlyName)", corpus) == corpus.has("traceX")


def test_observability_view_sheets_hold_their_view_and_the_shell():
    builder = load_builder()
    _, views = builder.observability_lists()
    assert set(views) == set(VIEWS)
    # A view's corpus leaves out the other views' markup and modules.
    logs = builder.observability_modules("logs")
    assert "app_logs.js" in logs and "app_traces.js" not in logs and "app_metrics.js" not in logs
    assert "app_observability.js" in logs and "app_timerange.js" in logs
    assert 'id="tracesForm"' not in builder.observability_html("logs")
    assert 'id="logsForm"' in builder.observability_html("logs")
    rules = {view: read(f"src/static/style.observability.{view}.css") for view in VIEWS}
    every = read("src/static/style.observability.css")
    # Each sheet styles the shell (the view tab row, view switching) and its own view only.
    for view, css in rules.items():
        assert ".obsNav {" in css and ".viewTab {" in css, view
        assert 'html:not([data-obs-view="traces"]) .obsView[data-obs-panel="traces"]' in css, view
        assert len(css) < len(every), view
    assert ".logsTable__viewport" in rules["logs"] and ".logsTable__viewport" not in rules["traces"]
    assert ".metricsPanels" in rules["metrics"] and ".metricsPanels" not in rules["logs"]
    assert ".traceWaterfall" in rules["traces"] and ".traceWaterfall" not in rules["metrics"]
    for name in (".logsTable__viewport", ".metricsPanels", ".traceWaterfall"):
        assert name in every, name
    # app_observability.js swaps in the every-view sheet once a second view is shown.
    controller = read("src/static/app_observability.js")
    assert 'const ALL_VIEWS_SHEET = "style.observability.css";' in controller
    assert "return views.size > 1 ? ALL_VIEWS_SHEET : `style.observability.${[...views][0]}.css`;" in controller


def test_query_and_explorer_skip_the_modules_they_never_run():
    builder = load_builder()
    app = read("src/static/app.js")
    assert "const skipped = new Set(PAGE_SKIPPED_MODULES[document.body?.dataset.page] || []);" in app
    assert "if (skipped.has(f)) continue;" in app
    query = builder.page_modules("query")
    explorer = builder.page_modules("explorer")
    assert {"app_explorer.js", "app_run.js", "app_autocomplete.js", "app_analysis.js"} <= set(query)
    assert "app_explorer_graph.js" not in query and "app_explorer_treemap.js" not in query
    assert {"app_explorer.js", "app_explorer_graph.js", "app_explorer_treemap.js", "app_results.js", "app_highlight.js"} <= set(explorer)
    for name in ["app_autocomplete.js", "app_run.js", "app_analysis.js", "app_pipeline_viewer.js", "app_trace_viewer.js", "app_download.js", "app_export.js"]:
        assert name not in explorer, name
