#!/usr/bin/env python3
"""Build one stylesheet per page shell from src/static/style.css.

style.css stays the only stylesheet anyone edits. Every page used to parse all
of it (3,000+ rules), although most rules style another page: each rule costs
renderer memory and style-recalc work whether or not it can ever match. This
script writes src/static/style.<page>.css, the subset of style.css that can match
on <page>, in the original order (so the cascade is unchanged for every rule a
page keeps) and next to style.css (so relative url()s resolve the same).

A rule is dropped from a page only when one of the class or id names its
selector requires appears nowhere in that page's sources: the page HTML plus,
transitively, every static .js file a source names ("app_x.js"), lazily loaded
modules included. A name counts as present when it is written in full, or when
a part of it ending at a "-"/"_" seam is followed by a quote or "${" (the name
is assembled at run time, e.g. "chdash-trace-tab-" + tab); id lookups such as
byId("x") or dom.x are not counted, since they only find what the HTML or a
script already created. Arguments of
functional pseudo-classes (:not(), :is(), :has(), ...) never cause a drop.
Everything else (element, attribute and :root rules, @keyframes, @font-face)
is kept.

Run after editing style.css, a page shell or a module's class names:
    python3 tools/build_page_css.py          # rewrite src/static/style.<page>.css
    python3 tools/build_page_css.py --check  # exit 1 if they are stale
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "src" / "static"
SOURCE = STATIC / "style.css"
PAGES = ("query", "explorer", "traces", "logs", "metrics")
HEADER = "/* Generated by tools/build_page_css.py from style.css for {page}.html: edit style.css, then rerun it. */\n"

SCRIPT_NAME = re.compile(r"""["'`/]([A-Za-z0-9_.-]+\.js)["'`]""")
TOKEN = re.compile(r"[.#](-?[A-Za-z_][A-Za-z0-9_-]*)")
FUNCTIONAL_PSEUDO = re.compile(r":[a-zA-Z-]+\(")
# Element lookups name an id the page HTML must already carry, so they are no
# evidence that the page creates that name (app_dom.js looks up every page's ids).
ELEMENT_LOOKUP = re.compile(
    r"""(?:\b[A-Za-z_$][\w$]*\s*:\s*)?\b(?:byId|getElementById)\(\s*(["'])[^"'`]*\1\s*\)|\bdom\??\.[A-Za-z_$][\w$]*"""
)


def page_corpus(page: str) -> str:
    """Page HTML plus every static script it can load, transitively."""
    texts = [(STATIC / f"{page}.html").read_text(encoding="utf-8")]
    seen: set[str] = set()
    i = 0
    while i < len(texts):
        for name in SCRIPT_NAME.findall(texts[i]):
            path = STATIC / name
            if name not in seen and path.is_file():
                seen.add(name)
                texts.append(path.read_text(encoding="utf-8"))
        i += 1
    return ELEMENT_LOOKUP.sub(" ", "\n".join(texts))


class Corpus:
    def __init__(self, text: str) -> None:
        self.text = text
        self.cache: dict[str, bool] = {}

    def has(self, token: str) -> bool:
        hit = self.cache.get(token)
        if hit is None:
            hit = self._has(token)
            self.cache[token] = hit
        return hit

    def _has(self, token: str) -> bool:
        if token in self.text:
            return True
        # Assembled names: a stem ending at a "-"/"_" seam, followed by the end of
        # a string literal or a template substitution.
        for cut in range(2, len(token)):
            if token[cut] in "-_" or token[cut - 1] in "-_":
                stem = token[:cut]
                for tail in ('"', "'", "`", "${"):
                    if stem + tail in self.text:
                        return True
        return False


def strip_functional_pseudo(selector: str) -> str:
    """Remove the parenthesised arguments of :not(), :is(), :has(), ..."""
    out = []
    i = 0
    while i < len(selector):
        m = FUNCTIONAL_PSEUDO.match(selector, i)
        if m:
            depth = 1
            j = m.end()
            while j < len(selector) and depth:
                if selector[j] == "(":
                    depth += 1
                elif selector[j] == ")":
                    depth -= 1
                j += 1
            out.append(" ")
            i = j
            continue
        out.append(selector[i])
        i += 1
    return "".join(out)


def split_selector_list(prelude: str) -> list[str]:
    parts, depth, start = [], 0, 0
    for i, ch in enumerate(prelude):
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append(prelude[start:i])
            start = i + 1
    parts.append(prelude[start:])
    return parts


def selector_can_match(selector: str, corpus: Corpus) -> bool:
    bare = re.sub(r"\[[^\]]*\]", " ", strip_functional_pseudo(selector))
    return all(corpus.has(token) for token in TOKEN.findall(bare))


# --- a small CSS reader: enough for style.css (no nesting, no @import) ------


def skip_comment_or_string(css: str, i: int) -> int:
    if css.startswith("/*", i):
        end = css.find("*/", i + 2)
        if end < 0:
            raise ValueError(f"unterminated comment at {i}")
        return end + 2
    if css[i] in "\"'":
        quote, j = css[i], i + 1
        while css[j] != quote:
            j += 2 if css[j] == "\\" else 1
        return j + 1
    return i


def read_block(css: str, i: int) -> int:
    """i is just past "{"; returns the index just past the matching "}"."""
    depth = 1
    while depth:
        j = skip_comment_or_string(css, i)
        if j != i:
            i = j
            continue
        if css[i] == "{":
            depth += 1
        elif css[i] == "}":
            depth -= 1
        i += 1
    return i


def strip_comments(text: str) -> str:
    out, i = [], 0
    while i < len(text):
        j = skip_comment_or_string(text, i)
        if j != i:
            if text[i] in "\"'":
                out.append(text[i:j])
            i = j
            continue
        out.append(text[i])
        i += 1
    return "".join(out)


def parse(css: str, start: int = 0, end: int | None = None) -> list[tuple]:
    """[(prelude, body_text)] for rules, [(prelude, [children])] for grouping at-rules."""
    end = len(css) if end is None else end
    items, i, prelude_start = [], start, start
    while i < end:
        j = skip_comment_or_string(css, i)
        if j != i:
            i = j
            continue
        ch = css[i]
        if ch == ";":  # statement at-rule (@charset, @import): keep verbatim
            items.append(("stmt", strip_comments(css[prelude_start : i + 1]).strip()))
            i += 1
            prelude_start = i
        elif ch == "{":
            prelude = strip_comments(css[prelude_start:i]).strip()
            close = read_block(css, i + 1)
            if prelude.startswith(("@media", "@supports", "@layer", "@container")):
                items.append(("group", prelude, parse(css, i + 1, close - 1)))
            else:
                items.append(("rule", prelude, css[i + 1 : close - 1]))
            i = close
            prelude_start = i
        else:
            i += 1
    return items


def render(items: list[tuple], corpus: Corpus, indent: str = "") -> list[str]:
    lines = []
    for item in items:
        if item[0] == "stmt":
            lines.append(indent + item[1])
        elif item[0] == "group":
            inner = render(item[2], corpus, indent + "  ")
            if inner:
                lines.append(f"{indent}{item[1]} {{")
                lines.extend(inner)
                lines.append(indent + "}")
        else:
            _, prelude, body = item
            keep = prelude.startswith("@") or any(selector_can_match(s, corpus) for s in split_selector_list(prelude))
            if keep:  # the declarations verbatim: custom property values keep their text
                lines.append(f"{indent}{prelude} {{{body}}}")
    return lines


def build() -> dict[Path, str]:
    items = parse(SOURCE.read_text(encoding="utf-8"))
    outputs = {}
    for page in PAGES:
        corpus = Corpus(page_corpus(page))
        outputs[STATIC / f"style.{page}.css"] = HEADER.format(page=page) + "\n".join(render(items, corpus)) + "\n"
    return outputs


def main(argv: list[str]) -> int:
    outputs = build()
    if "--check" in argv:
        stale = [p for p, text in outputs.items() if not p.is_file() or p.read_text(encoding="utf-8") != text]
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)} (run python3 tools/build_page_css.py)", file=sys.stderr)
        return 1 if stale else 0
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
