#!/usr/bin/env python3
"""Build one stylesheet per page shell (and per Observability view) from src/static/style.css.

style.css stays the only stylesheet anyone edits. Every page used to parse all
of it (3,000+ rules), although most rules style another page: each rule costs
renderer memory and style-recalc work whether or not it can ever match. This
script writes src/static/style.<page>.css, the subset of style.css that can match
on <page>, in the original order (so the cascade is unchanged for every rule a
page keeps) and next to style.css (so relative url()s resolve the same).

The Observability page (observability.html) loads one view first and the others
when they are first shown, so it has a sheet per view,
style.observability.<view>.css (the shell outside the other views' marked
sections, app_observability.js, the common modules and the view's modules),
and style.observability.css for every view at once, which app_observability.js
swaps in when a second view is shown: a superset in style.css order, so the
cascade never depends on which views were opened first.

A rule is dropped from a page only when one of the class or id names its
selector requires appears nowhere in that page's sources: the page HTML plus
every module src/static/modules.json lists for the page (app_loader.js, the
page controller, the common modules, the page's modules and its lazy groups;
on Observability, the views' modules). A name counts
as present when it is written in full, or when a part of it ending at a "-"/"_"
seam is followed by a quote or "${" (the name is assembled at run time, e.g.
"chdash-trace-tab-" + tab); id lookups such as byId("x") or dom.x are not
counted, since they only find what the HTML or a script already created.
Arguments of functional pseudo-classes (:not(), :is(), :has(), ...) never cause
a drop. Everything else (element, attribute and :root rules, @keyframes,
@font-face) is kept.

It first writes the generated regions of the page shells (tools/page_shells.py:
the header from src/shell/header.html, the module lists from modules.json).

Run after editing style.css, a page shell, src/shell/header.html, modules.json
or a module's class names:
    python3 tools/build_page_css.py          # rewrite the shells' regions and src/static/style.<page>.css
    python3 tools/build_page_css.py --check  # exit 1 if any of them is stale
"""
from __future__ import annotations

import re
import sys
from functools import lru_cache
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import page_shells  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "src" / "static"
SOURCE = STATIC / "style.css"
PAGES = ("query", "explorer")
HEADER = "/* Generated by tools/build_page_css.py from style.css for {page}.html: edit style.css, then rerun it. */\n"
OBSERVABILITY = "observability"
OBSERVABILITY_VIEWS = ("traces", "logs", "metrics")
OBSERVABILITY_CONTROLLER = "app_observability.js"
OBSERVABILITY_HEADER = "/* Generated by tools/build_page_css.py from style.css for observability.html ({views}): edit style.css, then rerun it. */\n"

TOKEN = re.compile(r"[.#](-?[A-Za-z_][A-Za-z0-9_-]*)")
FUNCTIONAL_PSEUDO = re.compile(r":[a-zA-Z-]+\(")
# Element lookups name an id the page HTML must already carry, so they are no
# evidence that the page creates that name (app_dom.js looks up every page's ids).
ELEMENT_LOOKUP = re.compile(
    r"""(?:\b[A-Za-z_$][\w$]*\s*:\s*)?\b(?:byId|getElementById)\(\s*(["'])[^"'`]*\1\s*\)|\bdom\??\.[A-Za-z_$][\w$]*"""
)


LOADER = "app_loader.js"


@lru_cache(maxsize=None)
def shells() -> dict[Path, str]:
    """The page shells with their generated regions current (what main() writes)."""
    return page_shells.build()


def shell_html(page: str) -> str:
    return shells()[STATIC / f"{page}.html"]


def page_modules(page: str) -> list[str]:
    """Every static script the page can load (modules.json), in load order."""
    entry = page_shells.page_entry(page)
    names = [LOADER, entry["bootstrap"], *entry["common"], *entry["modules"]]
    names += [name for files in entry["lazy"].values() for name in files]
    out: list[str] = []
    for name in names:
        assert (STATIC / name).is_file(), f"modules.json lists a missing file: {name}"
        if name not in out:
            out.append(name)
    return out


def page_corpus(page: str) -> str:
    """Page HTML plus every static script it can load."""
    texts = [shell_html(page)] + [(STATIC / name).read_text(encoding="utf-8") for name in page_modules(page)]
    return ELEMENT_LOOKUP.sub(" ", "\n".join(texts))


def observability_lists() -> tuple[list[str], dict[str, list[str]]]:
    """The modules every view loads, and each view's own (modules.json)."""
    entry = page_shells.page_entry(OBSERVABILITY)
    views = entry["views"]
    assert sorted(views) == sorted(OBSERVABILITY_VIEWS), views
    return [*entry["common"], *entry["modules"]], views


def observability_html(view: str | None = None) -> str:
    """The shell; for one view, without the other views' marked sections."""
    html = shell_html(OBSERVABILITY)
    for other in OBSERVABILITY_VIEWS:
        if view and other != view:
            section = re.compile(rf"<!-- {OBSERVABILITY}:{other} -->.*?<!-- /{OBSERVABILITY}:{other} -->", re.S)
            assert section.search(html), other
            html = section.sub("", html)
    return html


def observability_modules(view: str | None = None) -> list[str]:
    """The loader, the controller, the common modules and the view's (every view's) modules."""
    common, views = observability_lists()
    shown = [view] if view else list(OBSERVABILITY_VIEWS)
    names = [LOADER, OBSERVABILITY_CONTROLLER]
    for name in common + [f for v in shown for f in views[v]]:
        assert (STATIC / name).is_file(), f"modules.json lists a missing file: {name}"
        if name not in names:
            names.append(name)
    return names


def observability_corpus(view: str | None = None) -> str:
    texts = [observability_html(view)] + [(STATIC / name).read_text(encoding="utf-8") for name in observability_modules(view)]
    return ELEMENT_LOOKUP.sub(" ", "\n".join(texts))


class Corpus:
    def __init__(self, text: str) -> None:
        self.text = text
        self.cache: dict[str, bool] = {}

    def has(self, token: str) -> bool:
        hit = self.cache.get(token)
        if hit is None:
            hit = self._has(token)
            self.cache[token] = hit
        return hit

    def _has(self, token: str) -> bool:
        if token in self.text:
            return True
        # Assembled names: a stem ending at a "-"/"_" seam, followed by the end of
        # a string literal or a template substitution.
        for cut in range(2, len(token)):
            if token[cut] in "-_" or token[cut - 1] in "-_":
                stem = token[:cut]
                for tail in ('"', "'", "`", "${"):
                    if stem + tail in self.text:
                        return True
        return False


def strip_functional_pseudo(selector: str) -> str:
    """Remove the parenthesised arguments of :not(), :is(), :has(), ..."""
    out = []
    i = 0
    while i < len(selector):
        m = FUNCTIONAL_PSEUDO.match(selector, i)
        if m:
            depth = 1
            j = m.end()
            while j < len(selector) and depth:
                if selector[j] == "(":
                    depth += 1
                elif selector[j] == ")":
                    depth -= 1
                j += 1
            out.append(" ")
            i = j
            continue
        out.append(selector[i])
        i += 1
    return "".join(out)


def split_selector_list(prelude: str) -> list[str]:
    parts, depth, start = [], 0, 0
    for i, ch in enumerate(prelude):
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append(prelude[start:i])
            start = i + 1
    parts.append(prelude[start:])
    return parts


def selector_can_match(selector: str, corpus: Corpus) -> bool:
    bare = re.sub(r"\[[^\]]*\]", " ", strip_functional_pseudo(selector))
    return all(corpus.has(token) for token in TOKEN.findall(bare))


# --- a small CSS reader: enough for style.css (no nesting, no @import) ------


def skip_comment_or_string(css: str, i: int) -> int:
    if css.startswith("/*", i):
        end = css.find("*/", i + 2)
        if end < 0:
            raise ValueError(f"unterminated comment at {i}")
        return end + 2
    if css[i] in "\"'":
        quote, j = css[i], i + 1
        while css[j] != quote:
            j += 2 if css[j] == "\\" else 1
        return j + 1
    return i


def read_block(css: str, i: int) -> int:
    """i is just past "{"; returns the index just past the matching "}"."""
    depth = 1
    while depth:
        j = skip_comment_or_string(css, i)
        if j != i:
            i = j
            continue
        if css[i] == "{":
            depth += 1
        elif css[i] == "}":
            depth -= 1
        i += 1
    return i


def strip_comments(text: str) -> str:
    out, i = [], 0
    while i < len(text):
        j = skip_comment_or_string(text, i)
        if j != i:
            if text[i] in "\"'":
                out.append(text[i:j])
            i = j
            continue
        out.append(text[i])
        i += 1
    return "".join(out)


def parse(css: str, start: int = 0, end: int | None = None) -> list[tuple]:
    """[(prelude, body_text)] for rules, [(prelude, [children])] for grouping at-rules."""
    end = len(css) if end is None else end
    items, i, prelude_start = [], start, start
    while i < end:
        j = skip_comment_or_string(css, i)
        if j != i:
            i = j
            continue
        ch = css[i]
        if ch == ";":  # statement at-rule (@charset, @import): keep verbatim
            items.append(("stmt", strip_comments(css[prelude_start : i + 1]).strip()))
            i += 1
            prelude_start = i
        elif ch == "{":
            prelude = strip_comments(css[prelude_start:i]).strip()
            close = read_block(css, i + 1)
            if prelude.startswith(("@media", "@supports", "@layer", "@container")):
                items.append(("group", prelude, parse(css, i + 1, close - 1)))
            else:
                items.append(("rule", prelude, css[i + 1 : close - 1]))
            i = close
            prelude_start = i
        else:
            i += 1
    return items


def render(items: list[tuple], corpus: Corpus, indent: str = "") -> list[str]:
    lines = []
    for item in items:
        if item[0] == "stmt":
            lines.append(indent + item[1])
        elif item[0] == "group":
            inner = render(item[2], corpus, indent + "  ")
            if inner:
                lines.append(f"{indent}{item[1]} {{")
                lines.extend(inner)
                lines.append(indent + "}")
        else:
            _, prelude, body = item
            keep = prelude.startswith("@") or any(selector_can_match(s, corpus) for s in split_selector_list(prelude))
            if keep:  # the declarations verbatim: custom property values keep their text
                lines.append(f"{indent}{prelude} {{{body}}}")
    return lines


def build() -> dict[Path, str]:
    items = parse(SOURCE.read_text(encoding="utf-8"))
    outputs = {}
    for page in PAGES:
        corpus = Corpus(page_corpus(page))
        outputs[STATIC / f"style.{page}.css"] = HEADER.format(page=page) + "\n".join(render(items, corpus)) + "\n"
    for view in (*OBSERVABILITY_VIEWS, None):
        corpus = Corpus(observability_corpus(view))
        name = f"style.{OBSERVABILITY}.{view}.css" if view else f"style.{OBSERVABILITY}.css"
        header = OBSERVABILITY_HEADER.format(views=f"{view} view" if view else "every view")
        outputs[STATIC / name] = header + "\n".join(render(items, corpus)) + "\n"
    return outputs


def main(argv: list[str]) -> int:
    outputs = {**shells(), **build()}
    if "--check" in argv:
        stale = [p for p, text in outputs.items() if not p.is_file() or p.read_text(encoding="utf-8") != text]
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)} (run python3 tools/build_page_css.py)", file=sys.stderr)
        return 1 if stale else 0
    for path, text in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
