"""The icon sprite (src/static/icons.svg) and what is generated from it.

  version()      the sprite's content hash: pages ask for static/icons.svg?v=<hash>, an
                 address that never changes content, so the server lets browsers keep it
                 for a year (serve_embedded_static.hpp, cache_control_for).
  symbols()      {name: inner markup} of every <symbol id="i-<name>">.
  mask_tokens()  the "icons" region of src/static/css/00-tokens.css: a --icon-<name> data URI
                 for each MASK_ICONS drawing, for the pseudo-elements (select chevrons,
                 disclosure arrows, sort arrows) that cannot hold an <svg>. The URI is the
                 sprite's drawing with the .icon paint, so a masked icon and a sprite icon
                 are one drawing.

tools/build_page_css.py writes the token region and stamps the hash into the page shells;
its --check fails when either is stale. docs/ui-foundations.md, "Icons", has the rules.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
SPRITE = ROOT / "src" / "static" / "icons.svg"
TOKENS = ROOT / "src" / "static" / "css" / "00-tokens.css"
SYMBOL = re.compile(r'<symbol id="i-([a-z0-9-]+)" viewBox="0 0 24 24">(.*?)</symbol>', re.S)
# The paint of a sprite icon (css/10-components/icon.css, .icon), for the mask drawings.
PAINT = 'fill="none" stroke="#000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"'
# The drawings CSS paints as masks: name -> what uses it.
MASK_ICONS = {
    "chevron-down": "select, picker and split-button chevrons",
    "chevron-right": "<details> disclosure arrows",
    "selector": "a sortable column header on hover",
    "arrow-up": "a column sorted ascending",
    "arrow-down": "a column sorted descending",
}
REGION_START = "  /* icons:start - generated by tools/build_page_css.py from src/static/icons.svg (tools/icons.py); do not edit. */\n"
REGION_END = "  /* icons:end */\n"


def sprite_text() -> str:
    return SPRITE.read_text(encoding="ascii")


def version() -> str:
    return hashlib.sha256(SPRITE.read_bytes()).hexdigest()[:10]


def symbols() -> dict[str, str]:
    return {name: inner for name, inner in SYMBOL.findall(sprite_text())}


def mask_uri(name: str) -> str:
    svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {PAINT}>{symbols()[name]}</svg>'
    # Single-quoted attributes inside the url("...") token; only <, >, # and % need escaping.
    return "data:image/svg+xml," + quote(svg.replace('"', "'"), safe=" =:/'-.,")


def mask_tokens() -> str:
    lines = [f'  --icon-{name}: url("{mask_uri(name)}");\n' for name in MASK_ICONS]
    return REGION_START + "".join(lines) + REGION_END


def tokens_css(text: str | None = None) -> str:
    """00-tokens.css with its icons region rewritten."""
    text = TOKENS.read_text(encoding="utf-8") if text is None else text
    start = text.index(REGION_START.split(" - ")[0])
    end = text.index(REGION_END, start) + len(REGION_END)
    return text[:start] + mask_tokens() + text[end:]
