"""The generated parts of the page shells (query.html, explorer.html, observability.html).

Two regions of every shell are written from one source, so the shells cannot drift:

  <!-- shell:header --> ... <!-- /shell:header -->
      src/shell/header.html, the page header (brand, host picker, page and theme
      selects). Its placeholders take the page's values. Expanded at build time
      rather than rendered by a script, so the header is in the HTML the parser
      sees: it paints with the first frame, no flash, and costs no script.

  <!-- shell:scripts --> ... <!-- /shell:scripts -->
      the page's entry of src/static/modules.json, inlined as
      <script type="application/json" id="chdashModules"> so app_loader.js has
      the module lists without a request, then the two scripts that start the
      page: app_loader.js and the page controller (pages.<page>.bootstrap).

tools/build_page_css.py runs this before building the stylesheets (they read
the shells), and its --check fails when a shell is stale.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "src" / "static"
MANIFEST = STATIC / "modules.json"
HEADER = ROOT / "src" / "shell" / "header.html"
SHELLS = {"query": "Query", "explorer": "Explorer", "observability": "Observability"}


def manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def page_entry(page: str, data: dict | None = None) -> dict:
    """What a shell inlines for app_loader.js: the page's lists, the common ones first."""
    data = data or manifest()
    entry = data["pages"][page]
    return {
        "name": page,
        "bootstrap": entry["bootstrap"],
        "common": list(data["common"]),
        "modules": list(entry["modules"]),
        "lazy": dict(entry.get("lazy") or {}),
        "views": dict(entry.get("views") or {}),
    }


def header_markup(page: str) -> str:
    text = HEADER.read_text(encoding="utf-8")
    # The partial's leading comment documents it; the shells get the markup only.
    if text.startswith("<!--"):
        text = text[text.index("-->") + 3 :].lstrip("\n")
    values = {
        "{{page.label}}": SHELLS[page],
        "{{observability.hidden}}": "" if page == "observability" else " hidden",
    }
    for other in SHELLS:
        values[f"{{{{selected.{other}}}}}"] = "true" if other == page else "false"
    for key, value in values.items():
        text = text.replace(key, value)
    assert "{{" not in text, f"unknown placeholder in {HEADER.name}"
    return text


def scripts_markup(page: str, data: dict | None = None) -> str:
    entry = page_entry(page, data)
    payload = json.dumps(entry, separators=(",", ":")).replace("</", "<\\/")
    starts = "\n".join(
        f'      start(window.__chdashUrl ? window.__chdashUrl("static/{name}") : "/static/{name}");' for name in ("app_loader.js", entry["bootstrap"])
    )
    return (
        "  <!-- The page's modules (src/static/modules.json), read by app_loader.js. -->\n"
        f'  <script type="application/json" id="chdashModules">{payload}</script>\n'
        "  <script>\n"
        "    (function () {\n"
        "      // Both download at once and run in this order (async = false).\n"
        "      function start(src) {\n"
        '        var script = document.createElement("script");\n'
        "        script.src = src;\n"
        "        script.async = false;\n"
        "        document.body.appendChild(script);\n"
        "      }\n"
        f"{starts}\n"
        "    })();\n"
        "  </script>\n"
    )


def replace_region(html: str, name: str, body: str, source: str) -> str:
    """The text between the region's markers becomes a note and `body`."""
    start, end = f"<!-- shell:{name} -->", f"<!-- /shell:{name} -->"
    a = html.index(start) + len(start)
    b = html.index(end, a)
    note = f"  <!-- Generated by tools/build_page_css.py from {source}: edit it there, then rerun the script. -->\n"
    return html[:a] + "\n" + note + body + "  " + html[b:]


def build() -> dict[Path, str]:
    data = manifest()
    outputs = {}
    for page in SHELLS:
        path = STATIC / f"{page}.html"
        html = path.read_text(encoding="utf-8")
        html = replace_region(html, "header", header_markup(page), "src/shell/header.html")
        html = replace_region(html, "scripts", scripts_markup(page, data), "src/static/modules.json")
        outputs[path] = html
    return outputs
